#!/usr/bin/env python3
"""Display discovery and explicit, timed, reversible monitor transactions."""
import argparse
from datetime import datetime
import fcntl
import json
import os
from pathlib import Path
import re
import select
import signal
import subprocess
import sys
import time

from backend import atomic


def paths():
    config = Path(os.environ.get('XDG_CONFIG_HOME') or Path.home() / '.config')
    state = Path(os.environ.get('XDG_STATE_HOME') or Path.home() / '.local/state')
    return config / 'hyprshell', state / 'hyprshell'


def hypr(*args):
    result = subprocess.run(['hyprctl', *args], capture_output=True, text=True, timeout=5)
    if result.returncode:
        detail = (result.stderr or result.stdout).strip()
        if detail.startswith('usage:'):
            raise ValueError('Hyprland rejected the display command. Refresh and try again.')
        summary = next((line.strip() for line in detail.splitlines() if line.strip()), 'Command failed')[:240]
        raise ValueError('Cannot access Hyprland: ' + summary)
    return result.stdout


def monitors():
    data = json.loads(hypr('-j', 'monitors', 'all'))
    return [m for m in data if not m.get('disabled', False)]


def validate(data):
    if not isinstance(data, dict) or set(data) != {'version', 'entries'} or type(data['version']) is not int or data['version'] != 1:
        raise ValueError('Unsupported display preferences')
    if not isinstance(data['entries'], list) or len(data['entries']) > 32:
        raise ValueError('Expected a list of display preferences')
    seen = set()
    for entry in data['entries']:
        if not isinstance(entry, dict) or set(entry) != {'output', 'mode', 'scale', 'transform', 'position'}:
            raise ValueError('Invalid display preference fields')
        name = entry['output']
        if not isinstance(name, str) or not re.fullmatch(r'[A-Za-z0-9_.:-]{1,128}', name) or name in seen:
            raise ValueError('Invalid or duplicate output')
        seen.add(name)
        if not isinstance(entry['mode'], str) or not re.fullmatch(r'preferred|[1-9][0-9]{1,4}x[1-9][0-9]{1,4}@[0-9]+(?:\.[0-9]+)?(?:Hz)?', entry['mode']):
            raise ValueError('Invalid resolution or refresh rate')
        scale = entry['scale']
        if scale != 'auto' and (type(scale) not in (int, float) or not 0.5 <= scale <= 4):
            raise ValueError('Scale must be Auto or between 50% and 400%')
        if type(entry['transform']) is not int or not 0 <= entry['transform'] <= 7:
            raise ValueError('Invalid rotation')
        if not isinstance(entry['position'], str) or not re.fullmatch(r'auto|-?[0-9]{1,5}x-?[0-9]{1,5}', entry['position']):
            raise ValueError('Position must be Auto or logical X/Y coordinates')
    return data


def render(data, *, header=True):
    validate(data)
    rows = ['-- Generated by Hyprshell Displays; only confirmed preferences.'] if header else []
    for entry in data['entries']:
        fields = ', '.join(key + ' = ' + json.dumps(value) for key, value in entry.items())
        rows.append('hl.monitor({' + fields + '})')
    return '\n'.join(rows) + '\n'


def read_saved():
    config, _ = paths()
    target = config / 'displays.json'
    return validate(json.loads(target.read_text())) if target.exists() else {'version': 1, 'entries': []}


def live_entry(monitor):
    return {'output': monitor['name'], 'mode': f"{monitor['width']}x{monitor['height']}@{monitor['refreshRate']:.3f}",
            'scale': monitor['scale'], 'transform': monitor.get('transform', 0),
            'position': f"{monitor['x']}x{monitor['y']}"}


def status():
    saved = read_saved()
    connected = monitors()
    entries = []
    for monitor in connected:
        entry = live_entry(monitor)
        # Display actual state, keeping explicitly saved Auto settings when possible.
        previous = next((e for e in saved['entries'] if e['output'] == monitor['name']), {})
        for key in ('mode', 'scale', 'position'):
            if previous.get(key) in ('auto', 'preferred'):
                entry[key] = previous[key]
        entries.append(entry)
    return {'ok': True, 'saved': saved, 'entries': entries, 'monitors': connected}


def apply(entries):
    if entries:
        # hyprctl parses arguments starting with '--' as CLI flags, even after eval.
        result = hypr('eval', render({'version': 1, 'entries': entries}, header=False))
        if result.strip().lower() != 'ok':
            raise ValueError('Hyprland rejected the display change: ' + result.strip())


def persist(data, expected):
    config, state = paths()
    if read_saved() != expected:
        raise ValueError('Display preferences changed elsewhere. Refresh before applying.')
    targets = {config / 'displays.json': json.dumps(data, indent=2) + '\n',
               config / 'displays.lua': render(data)}
    previous = {p: p.read_text() if p.exists() else None for p in targets}
    backup = state / 'backups' / ('displays-' + datetime.now().strftime('%Y%m%d-%H%M%S-%f'))
    backup.mkdir(parents=True)
    manifest = []
    for index, (path, content) in enumerate(previous.items()):
        manifest.append({'path': str(path), 'existed': content is not None, 'file': str(index)})
        if content is not None:
            (backup / str(index)).write_text(content)
    (backup / 'manifest.json').write_text(json.dumps(manifest, indent=2))
    try:
        for path, content in targets.items():
            atomic(path, content)
    except Exception:
        for path, content in previous.items():
            if content is None:
                path.unlink(missing_ok=True)
            else:
                atomic(path, content)
        raise


def preview(request, emit, wait=None):
    config, state = paths()
    state.mkdir(parents=True, exist_ok=True)
    with (state / 'displays.lock').open('w') as lock:
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            raise ValueError('Another display change is awaiting confirmation.')
        expected = validate(request['expected'])
        if read_saved() != expected:
            raise ValueError('Display preferences changed elsewhere. Refresh before applying.')
        proposed = validate({'version': 1, 'entries': request['entries']})
        connected = monitors()
        by_name = {m['name']: m for m in connected}
        if not connected or {e['output'] for e in proposed['entries']} != set(by_name):
            raise ValueError('Connected displays changed. Refresh before applying.')
        for entry in proposed['entries']:
            m = by_name[entry['output']]
            current = live_entry(m)['mode']
            if entry['mode'] not in ['preferred', current] + m.get('availableModes', []):
                raise ValueError('Select a resolution and refresh rate advertised by the display.')
        original = [live_entry(m) for m in connected]
        saved = {'version': 1, 'entries': [e for e in expected['entries'] if e['output'] not in by_name] + proposed['entries']}
        kept = False
        try:
            apply(proposed['entries'])
            emit({'ok': True, 'pending': True, 'seconds': 15, 'message': 'Keep these display settings? They revert automatically in 15 seconds.'})
            decision = (wait or wait_for_confirmation)()
            if decision == 'keep':
                # Hotplug while confirming requires a fresh transaction.
                if {m['name'] for m in monitors()} != set(by_name):
                    raise ValueError('Connected displays changed during confirmation. Refresh and try again.')
                persist(saved, expected)
                kept = True
        finally:
            if not kept:
                # Reload restores base rules (including advanced monitor options),
                # then reapply the previous live geometry for still-connected outputs.
                hypr('reload')
                remaining = {m['name'] for m in monitors()}
                apply([e for e in original if e['output'] in remaining])
        return {'ok': True, 'pending': False, 'message': 'Display settings saved.' if kept else 'Previous display settings restored.'}


def wait_for_confirmation():
    deadline = time.monotonic() + 15
    ready, _, _ = select.select([sys.stdin], [], [], max(0, deadline - time.monotonic()))
    return sys.stdin.readline().strip() if ready and time.monotonic() < deadline else 'revert'


def interrupted(signum, frame):
    raise RuntimeError('Display preview interrupted; restoring previous settings.')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--request-json', required=True)
    args = parser.parse_args()
    signal.signal(signal.SIGTERM, interrupted)
    signal.signal(signal.SIGHUP, interrupted)
    def emit(result):
        print(json.dumps(result), flush=True)
    try:
        request = json.loads(args.request_json)
        if request['operation'] == 'status':
            result = status()
        elif request['operation'] == 'preview':
            result = preview(request, emit)
        else:
            raise ValueError('Unknown display action')
        emit(result)
        return 0
    except Exception as error:
        emit({'ok': False, 'pending': False, 'message': str(error)})
        return 1


if __name__ == '__main__':
    sys.exit(main())
