background {
    monitor =
    color = rgba(181825ff)
}

input-field {
    monitor =
    size = 300, 60
    position = 0, 0
    halign = center
    valign = center
    placeholder_text = Enter password
}
