-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        border_size = 3,
        col = {
            active_border = {
                colors = {"rgba(26a269ff)", "rgba(26a269ff)"},
                angle = 50,
            },
        },
        gaps_out = 10,
        resize_on_border = true,
    },
    gestures = {
        workspace_swipe_forever = true,
    },
    misc = {
        vrr = 1,
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@60.01Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
