# Bluetooth popup theme. Colors use RRGGBBAA.
[main]
font=GoMono Nerd Font:size=10
namespace=bluetooth-menu
x-margin=12
y-margin=40
width=30
line-height=40
horizontal-pad=18
vertical-pad=18
inner-pad=12

[colors]
background=181825f2
text=cdd6f4ff
message=cdd6f4ff
prompt=b4befeff
input=cdd6f4ff
placeholder=7f849cff
match=b4befeff
selection=313244cc
selection-text=b4befeff
selection-match=b4befeff
border=cdd6f426

[border]
width=1
radius=12
selection-radius=8
